Repository wecode-bootcamp-korea/16-2nd-starbugs-backend, pull requests merged in 2021-02, with the labels that each got.

#10 Add: 장진욱 socialloginview
  db_uploader.py
  starbugs/urls.py
  user/migrations/0003_auto_20210129_1306.py
  user/models.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: Accepted

#11 김진수 models.py 수정
  order/admin.py
  order/models.py
  order/tests.py
  order/views.py
  product/admin.py
  product/models.py
  product/views.py
  starbugs/asgi.py
  starbugs/settings.py
  starbugs/wsgi.py
  user/admin.py
  user/apps.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청

#12 models 수정했습니다!!!!!!!!!!!!!!!!!!!1
  order/admin.py
  order/apps.py
  product/admin.py
  product/models.py
  user/admin.py
  user/models.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#8 Add: 장진욱 ProductDetailView
  .gitignore
  db_uploader.py
  order/models.py
  product/migrations/0003_auto_20210201_1230.py
  product/models.py
  product/tests.py
  product/urls.py
  product/utils.py
  product/views.py
  starbugs/urls.py
  user/migrations/0004_remove_user_drink_propensity.py
  user/migrations/0005_auto_20210201_1230.py
  user/models.py
  user/views.py
Labels: Status: 리뷰 요청

#14 models.py 수정
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210129_0629.py
  order/models.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210129_0629.py
  product/models.py
  product/tests.py
  product/views.py
  starbugs/urls.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210129_0629.py
  user/migrations/0003_auto_20210129_1306.py
  user/models.py
Labels: Status: 리뷰 요청

#15 models.py 수정
  db_uploader.py
  order/migrations/0001_initial.py
  product/migrations/0001_initial.py
  product/migrations/0003_auto_20210201_1230.py
  product/urls.py
  starbugs/urls.py
  user/migrations/0001_initial.py
  user/migrations/0004_remove_user_drink_propensity.py
  user/migrations/0005_auto_20210201_1230.py
Labels: Status: 리뷰 요청

#16 model.py 수정
  .gitignore
  db_uploader.py
Labels: Status: 수정 요청

#18 models.py order와 orderstatus부분 수정
  order/models.py
Labels: Status: 리뷰 요청

#19 model 수정
  order/models.py
  order/tests.py
  product/models.py
  user/models.py
Labels: Status: Accepted

#7 Add : 김진수 Product list 수정 완료
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210202_0924.py
  order/tests.py
  product/migrations/0001_initial.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  starbugs/urls.py
  user/migrations/0001_initial.py
Labels: Status: 리뷰 진행중

#13 MODIFY : SocialLogin
  order/migrations/0001_initial.py
  order/models.py
  product/migrations/0001_initial.py
  product/tests.py
  product/urls.py
  product/views.py
  starbugs/urls.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210202_1032.py
  user/models.py
  user/tests.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#21 hot fix!!!
  product/tests.py
  product/urls.py
  product/views.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청

#17 MODIFY: 장진욱 ProductDetailView
  product/models.py
  product/urls.py
  product/views.py
  requirements.txt
Labels: Status: 리뷰 요청

#25 Feature/productdetail 프론트와 key값 조율
  product/views.py
  requirements.txt
Labels: Status: 리뷰 진행중

#22 ADD : cartview, cartviewtest
  order/tests.py
  order/urls.py
  order/views.py
  starbugs/urls.py
Labels: Status: 리뷰 요청

#27 Conflict 해결, 리뷰 반영
  .gitignore
  .vscode/settings.json
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210202_0924.py
  product/migrations/0001_initial.py
  product/test_temp.py
  product/tests.py
  product/urls.py
  product/utils.py
  product/views.py
  starbugs/settings.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210202_1032.py
  user/models.py
  user/utils.py
Labels: Status: 리뷰 요청
